#!/usr/bin/env python3
"""
Setup script for NASA API keys configuration

This script helps users set up their .env file with NASA API keys.
"""

import os
import sys
from pathlib import Path

def main():
    """Interactive setup for NASA API keys"""
    print("🔥 Wildfire Nowcast Agent - NASA API Keys Setup")
    print("=" * 50)
    print()
    
    env_file = Path(".env")
    template_file = Path(".env.template")
    
    # Check if .env already exists
    if env_file.exists():
        print("⚠️  .env file already exists!")
        response = input("Do you want to overwrite it? (y/N): ").strip().lower()
        if response != 'y':
            print("Setup cancelled.")
            return
    
    # Check if template exists
    if not template_file.exists():
        print("❌ .env.template file not found!")
        print("Please make sure you're running this script from the project root directory.")
        sys.exit(1)
    
    print("📋 Please provide your NASA API keys:")
    print("   (Only FIRMS requires an API key - GIBS and EONET are publicly accessible)")
    print()
    
    # Get NASA API keys
    nasa_firms_key = input("NASA FIRMS API Key (required): ").strip()
    nasa_gibs_key = input("NASA GIBS API Key (optional - not required): ").strip()
    nasa_eonet_key = input("NASA EONET API Key (optional - not required): ").strip()
    
    # Validate required key
    if not nasa_firms_key:
        print("❌ NASA FIRMS API Key is required!")
        print("Get your free key at: https://firms.modaps.eosdis.nasa.gov/api/")
        sys.exit(1)
    
    # Create .env file
    env_content = f"""# NASA API Configuration
# Generated by setup_env.py

# NASA FIRMS API Key (required for enhanced fire hotspot data)
NASA_FIRMS_API_KEY={nasa_firms_key}

# NASA GIBS API Key (optional, for enhanced satellite imagery access)
NASA_GIBS_API_KEY={nasa_gibs_key or 'your_gibs_api_key_here'}

# NASA EONET API Key (optional, for enhanced event data)
NASA_EONET_API_KEY={nasa_eonet_key or 'your_eonet_api_key_here'}

# AWS Configuration (optional - will use AWS CLI defaults if not set)
# AWS_REGION=us-east-1
# AWS_PROFILE=default
"""
    
    with open(env_file, 'w') as f:
        f.write(env_content)
    
    print()
    print("✅ .env file created successfully!")
    print()
    print("📋 Next steps:")
    print("1. Install dependencies: uv sync")
    print("2. Deploy the agent: uv run python deploy.py")
    print()
    print("🔗 Get NASA API keys:")
    print("- FIRMS (required): https://firms.modaps.eosdis.nasa.gov/api/")
    print("- GIBS (optional): https://nasa-gibs.github.io/gibs-api-docs/python-usage")
    print("- EONET (optional): https://eonet.gsfc.nasa.gov/docs/v3")

if __name__ == "__main__":
    main()
